class Demo {
	public static void func(){
		try {
			throw new Exception();
			//System.out.println("A");  //can't write anything under throw
		} catch (Exception e) {
			System.out.println("B");
		}
	}

	public static void main(String[] args) {
		try {
			func();
		}catch(Exception e) {
			System.out.println("C");
		}
		System.out.println("D");
	}
}
